export const PRODUCT_CATEGORIES = [
  "Hot Drinks",
  "Cold Drinks",
  "Alcohol",
  "Cocktails",
  "Breakfast",
  "Soups",
  "Salads",
  "Appetizers",
  "Main Dishes",
  "Grill",
  "Pasta",
  "Pizza",
  "Sandwiches",
  "Traditional Food",
  "Side Dishes",
  "Desserts",
  "Oferte",
];
